//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public string ContentSide { get; set; }
        public string HomePageSide { get; set; }
        public string HomePageMainLarge { get; set; }
        public string HomePageMainSmall { get; set; }
    }
}
