//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifyService
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> SaleTypeID { get; set; }
        public Nullable<int> RealEstateTypeID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Area { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual District District { get; set; }
        public virtual RealEstateType RealEstateType { get; set; }
        public virtual SaleType SaleType { get; set; }
    }
}
