//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateProjectModel
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> RealEstateTypeID { get; set; }
        public string Title { get; set; }
        public string EnTitle { get; set; }
        public string Description { get; set; }
        public string EnDescription { get; set; }
        public string PlanImgURL { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual RealEstateProject RealEstateProject { get; set; }
        public virtual RealEstateType RealEstateType { get; set; }
    }
}
