//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RealEstate()
        {
            this.RealEstatePhotos = new HashSet<RealEstatePhoto>();
            this.RealEstateSuspendeds = new HashSet<RealEstateSuspended>();
            this.RealEstateCriterias = new HashSet<RealEstateCriteria>();
            this.RealEstateComplains = new HashSet<RealEstateComplain>();
            this.RealEstatePurchaseRequests = new HashSet<RealEstatePurchaseRequest>();
            this.SubscriberFavouriteRealEstates = new HashSet<SubscriberFavouriteRealEstate>();
            this.RealestateCatalogProperties = new HashSet<RealestateCatalogProperty>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SubscriberID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> RealEstateCategoryID { get; set; }
        public Nullable<int> RealEstateStatusID { get; set; }
        public Nullable<int> RealEstateTypeID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> SaleTypeId { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public int Code { get; set; }
        public string Street { get; set; }
        public string EnStreet { get; set; }
        public string Title { get; set; }
        public string EnTitle { get; set; }
        public string Description { get; set; }
        public string EnDescription { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Area { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string OwnerName { get; set; }
        public string OwnerMobile { get; set; }
        public string OwnerEmail { get; set; }
        public Nullable<bool> IsSold { get; set; }
        public Nullable<int> ActiveStatusId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> UseContactInfo { get; set; }
        public Nullable<bool> IsMigrated { get; set; }
        public Nullable<bool> IsSpecialOffer { get; set; }
        public Nullable<System.DateTime> ChangeActiveStatus { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual District District { get; set; }
        public virtual RealEstateCategory RealEstateCategory { get; set; }
        public virtual RealEstateProject RealEstateProject { get; set; }
        public virtual RealEstateStatu RealEstateStatu { get; set; }
        public virtual RealEstateType RealEstateType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RealEstatePhoto> RealEstatePhotos { get; set; }
        public virtual Subscriber Subscriber { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual SaleType SaleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RealEstateSuspended> RealEstateSuspendeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RealEstateCriteria> RealEstateCriterias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RealEstateComplain> RealEstateComplains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RealEstatePurchaseRequest> RealEstatePurchaseRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriberFavouriteRealEstate> SubscriberFavouriteRealEstates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RealestateCatalogProperty> RealestateCatalogProperties { get; set; }
    }
}
