//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateProjectVideo
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string TiTle { get; set; }
        public string EnTitle { get; set; }
        public string URL { get; set; }
        public string EmedCode { get; set; }
    
        public virtual RealEstateProject RealEstateProject { get; set; }
    }
}
