//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RealEstateProject()
        {
            this.RealEstateProjectPhotos = new HashSet<RealEstateProjectPhoto>();
            this.RealEstateProjectVideos = new HashSet<RealEstateProjectVideo>();
            this.RealEstateProjectModels = new HashSet<RealEstateProjectModel>();
            this.RealEstates = new HashSet<RealEstate>();
            this.CompanyMessages = new HashSet<CompanyMessage>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SubscriberID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Code { get; set; }
        public string Sologan { get; set; }
        public string EnSologan { get; set; }
        public string Title { get; set; }
        public string EnTitle { get; set; }
        public string Description { get; set; }
        public string EnDesctiption { get; set; }
        public string Logo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ActiveStatusID { get; set; }
        public Nullable<int> AdPackageID { get; set; }
        public Nullable<int> SuspendReasonID { get; set; }
        public string SuspendMessage { get; set; }
        public Nullable<System.DateTime> StatusChangeDate { get; set; }
        public string Summary { get; set; }
        public string EnSummary { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual District District { get; set; }
        public virtual RealEstateCompany RealEstateCompany { get; set; }
        public virtual SuspendReason SuspendReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RealEstateProjectPhoto> RealEstateProjectPhotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RealEstateProjectVideo> RealEstateProjectVideos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RealEstateProjectModel> RealEstateProjectModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RealEstate> RealEstates { get; set; }
        public virtual Subscriber Subscriber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyMessage> CompanyMessages { get; set; }
    }
}
