//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateSuspended
    {
        public int ID { get; set; }
        public Nullable<int> RealEstateID { get; set; }
        public Nullable<int> SuspendReasonId { get; set; }
        public string Message { get; set; }
    
        public virtual RealEstate RealEstate { get; set; }
        public virtual SuspendReason SuspendReason { get; set; }
    }
}
