//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateComplain
    {
        public int ID { get; set; }
        public Nullable<int> RealEstateID { get; set; }
        public string ComplainerName { get; set; }
        public string ComplainerEmail { get; set; }
        public string ComplainerPhone { get; set; }
        public string ComplainTitle { get; set; }
        public string ComplainDetails { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual RealEstate RealEstate { get; set; }
    }
}
