//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriperMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubscriperMessage()
        {
            this.ReplyMessages = new HashSet<SubscriperMessage>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MessageTypeID { get; set; }
        public Nullable<int> ParentMessageID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string Body { get; set; }
        public Nullable<int> From { get; set; }
        public Nullable<int> To { get; set; }
        public Nullable<bool> FromSubscriber { get; set; }
        public Nullable<bool> IsClosed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriperMessage> ReplyMessages { get; set; }
        public virtual SubscriperMessage ParentMessage { get; set; }
        public virtual SubscriperMessageType SubscriperMessageType { get; set; }
    }
}
