//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerDLL.SMSServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSServiceReference.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendFailedSSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendFailedSSMS(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendFailedWapPush", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendFailedWapPush(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendSMS(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver);
        
        // CODEGEN: Generating message contract since the wrapper name (SendSMSWithOperator) of message SendSMSWithOperator does not match the default value (SendSMS1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSWithOperator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BrokerDLL.SMSServiceReference.SendSMSWithOperator1 SendSMS1(BrokerDLL.SMSServiceReference.SendSMSWithOperator request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOneSMSToMany", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] SendOneSMSToMany(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver);
        
        // CODEGEN: Generating message contract since the wrapper name (SendOneSMSToManyWithOperator) of message SendOneSMSToManyWithOperator does not match the default value (SendOneSMSToMany1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOneSMSToManyWithOperator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BrokerDLL.SMSServiceReference.SendOneSMSToManyWithOperator1 SendOneSMSToMany1(BrokerDLL.SMSServiceReference.SendOneSMSToManyWithOperator request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int CheckCredit(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWapPush", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int SendWapPush(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver);
        
        // CODEGEN: Generating message contract since the wrapper name (SendWapPushWithOperator) of message SendWapPushWithOperator does not match the default value (SendWapPush1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWapPushWithOperator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BrokerDLL.SMSServiceReference.SendWapPushWithOperator1 SendWapPush1(BrokerDLL.SMSServiceReference.SendWapPushWithOperator request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOneWAPPushToMany_WithDLR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] SendOneWAPPushToMany_WithDLR(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver);
        
        // CODEGEN: Generating message contract since the wrapper name (SendOneWAPPushToMany_WithDLRWithOperator) of message SendOneWAPPushToMany_WithDLRWithOperator does not match the default value (SendOneWAPPushToMany_WithDLR1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOneWAPPushToMany_WithDLRWithOperator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BrokerDLL.SMSServiceReference.SendOneWAPPushToMany_WithDLRWithOperator1 SendOneWAPPushToMany_WithDLR1(BrokerDLL.SMSServiceReference.SendOneWAPPushToMany_WithDLRWithOperator request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOneWAPPushToMany", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] SendOneWAPPushToMany(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver);
        
        // CODEGEN: Generating message contract since the wrapper name (SendOneWAPPushToManyWithOperator) of message SendOneWAPPushToManyWithOperator does not match the default value (SendOneWAPPushToMany1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOneWAPPushToManyWithOperator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BrokerDLL.SMSServiceReference.SendOneWAPPushToManyWithOperator1 SendOneWAPPushToMany1(BrokerDLL.SMSServiceReference.SendOneWAPPushToManyWithOperator request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_WithDLR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int SendSMS_WithDLR(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSWithDLR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int SendSMSWithDLR(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWapPush_WithDLR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int SendWapPush_WithDLR(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver);
        
        // CODEGEN: Generating message contract since the wrapper name (SendWapPush_WithDLRWithOperator) of message SendWapPush_WithDLRWithOperator does not match the default value (SendWapPush_WithDLR1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWapPush_WithDLRWithOperator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BrokerDLL.SMSServiceReference.SendWapPush_WithDLRWithOperator1 SendWapPush_WithDLR1(BrokerDLL.SMSServiceReference.SendWapPush_WithDLRWithOperator request);
        
        // CODEGEN: Generating message contract since the wrapper name (SendSMS_WithDLRWithOperator) of message SendSMS_WithDLRWithOperator does not match the default value (SendSMS_WithDLR1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_WithDLRWithOperator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BrokerDLL.SMSServiceReference.SendSMS_WithDLRWithOperator1 SendSMS_WithDLR1(BrokerDLL.SMSServiceReference.SendSMS_WithDLRWithOperator request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendManySMS_WithDLR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] SendManySMS_WithDLR(System.Data.DataSet DS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendManyWAPPush_WithDLR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] SendManyWAPPush_WithDLR(System.Data.DataSet ds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOneSMSToMany_WithDLR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] SendOneSMSToMany_WithDLR(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver);
        
        // CODEGEN: Generating message contract since the wrapper name (SendOneSMSToMany_WithDLRWithOperator) of message SendOneSMSToMany_WithDLRWithOperator does not match the default value (SendOneSMSToMany_WithDLR1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOneSMSToMany_WithDLRWithOperator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BrokerDLL.SMSServiceReference.SendOneSMSToMany_WithDLRWithOperator1 SendOneSMSToMany_WithDLR1(BrokerDLL.SMSServiceReference.SendOneSMSToMany_WithDLRWithOperator request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendUnicodeMsgs_WithDLR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int SendUnicodeMsgs_WithDLR(string UserName, string Password, string SMSSender, string SMSReceiver, string DCS, string Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendUnicodeMsgs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int SendUnicodeMsgs(string UserName, string Password, string SMSSender, string SMSReceiver, string DCS, string Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendUnicodeMsgsWithOperator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int SendUnicodeMsgsWithOperator(string UserName, string Password, string SMSSender, string SMSReceiver, string DCS, string Data, BrokerDLL.SMSServiceReference.Operators OperatorName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum Operators {
        
        /// <remarks/>
        Mobinil,
        
        /// <remarks/>
        Vodafone,
        
        /// <remarks/>
        Etisalat,
        
        /// <remarks/>
        International,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSWithOperator", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMSWithOperator {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SMSText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string SMSLang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string SMSSender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string SMSReceiver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public BrokerDLL.SMSServiceReference.Operators OperatorName;
        
        public SendSMSWithOperator() {
        }
        
        public SendSMSWithOperator(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            this.UserName = UserName;
            this.Password = Password;
            this.SMSText = SMSText;
            this.SMSLang = SMSLang;
            this.SMSSender = SMSSender;
            this.SMSReceiver = SMSReceiver;
            this.OperatorName = OperatorName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSWithOperatorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMSWithOperator1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendSMSWithOperatorResult;
        
        public SendSMSWithOperator1() {
        }
        
        public SendSMSWithOperator1(int SendSMSWithOperatorResult) {
            this.SendSMSWithOperatorResult = SendSMSWithOperatorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendOneSMSToManyWithOperator", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendOneSMSToManyWithOperator {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SMSText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string SMSLang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string SMSSender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string SMSReceiver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public BrokerDLL.SMSServiceReference.Operators OperatorName;
        
        public SendOneSMSToManyWithOperator() {
        }
        
        public SendOneSMSToManyWithOperator(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            this.UserName = UserName;
            this.Password = Password;
            this.SMSText = SMSText;
            this.SMSLang = SMSLang;
            this.SMSSender = SMSSender;
            this.SMSReceiver = SMSReceiver;
            this.OperatorName = OperatorName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendOneSMSToManyWithOperatorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendOneSMSToManyWithOperator1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object[] SendOneSMSToManyWithOperatorResult;
        
        public SendOneSMSToManyWithOperator1() {
        }
        
        public SendOneSMSToManyWithOperator1(object[] SendOneSMSToManyWithOperatorResult) {
            this.SendOneSMSToManyWithOperatorResult = SendOneSMSToManyWithOperatorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendWapPushWithOperator", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendWapPushWithOperator {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string StrLink;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string StrDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string SMSSender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string SMSReceiver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public BrokerDLL.SMSServiceReference.Operators OperatorName;
        
        public SendWapPushWithOperator() {
        }
        
        public SendWapPushWithOperator(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            this.UserName = UserName;
            this.Password = Password;
            this.StrLink = StrLink;
            this.StrDescription = StrDescription;
            this.SMSSender = SMSSender;
            this.SMSReceiver = SMSReceiver;
            this.OperatorName = OperatorName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendWapPushWithOperatorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendWapPushWithOperator1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendWapPushWithOperatorResult;
        
        public SendWapPushWithOperator1() {
        }
        
        public SendWapPushWithOperator1(int SendWapPushWithOperatorResult) {
            this.SendWapPushWithOperatorResult = SendWapPushWithOperatorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendOneWAPPushToMany_WithDLRWithOperator", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendOneWAPPushToMany_WithDLRWithOperator {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string StrLink;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string StrDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string SMSSender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string SMSReceiver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public BrokerDLL.SMSServiceReference.Operators OperatorName;
        
        public SendOneWAPPushToMany_WithDLRWithOperator() {
        }
        
        public SendOneWAPPushToMany_WithDLRWithOperator(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            this.UserName = UserName;
            this.Password = Password;
            this.StrLink = StrLink;
            this.StrDescription = StrDescription;
            this.SMSSender = SMSSender;
            this.SMSReceiver = SMSReceiver;
            this.OperatorName = OperatorName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendOneWAPPushToMany_WithDLRWithOperatorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendOneWAPPushToMany_WithDLRWithOperator1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object[] SendOneWAPPushToMany_WithDLRWithOperatorResult;
        
        public SendOneWAPPushToMany_WithDLRWithOperator1() {
        }
        
        public SendOneWAPPushToMany_WithDLRWithOperator1(object[] SendOneWAPPushToMany_WithDLRWithOperatorResult) {
            this.SendOneWAPPushToMany_WithDLRWithOperatorResult = SendOneWAPPushToMany_WithDLRWithOperatorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendOneWAPPushToManyWithOperator", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendOneWAPPushToManyWithOperator {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string StrLink;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string StrDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string SMSSender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string SMSReceiver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public BrokerDLL.SMSServiceReference.Operators OperatorName;
        
        public SendOneWAPPushToManyWithOperator() {
        }
        
        public SendOneWAPPushToManyWithOperator(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            this.UserName = UserName;
            this.Password = Password;
            this.StrLink = StrLink;
            this.StrDescription = StrDescription;
            this.SMSSender = SMSSender;
            this.SMSReceiver = SMSReceiver;
            this.OperatorName = OperatorName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendOneWAPPushToManyWithOperatorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendOneWAPPushToManyWithOperator1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object[] SendOneWAPPushToManyWithOperatorResult;
        
        public SendOneWAPPushToManyWithOperator1() {
        }
        
        public SendOneWAPPushToManyWithOperator1(object[] SendOneWAPPushToManyWithOperatorResult) {
            this.SendOneWAPPushToManyWithOperatorResult = SendOneWAPPushToManyWithOperatorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendWapPush_WithDLRWithOperator", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendWapPush_WithDLRWithOperator {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string StrLink;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string StrDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string SMSSender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string SMSReceiver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public BrokerDLL.SMSServiceReference.Operators OperatorName;
        
        public SendWapPush_WithDLRWithOperator() {
        }
        
        public SendWapPush_WithDLRWithOperator(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            this.UserName = UserName;
            this.Password = Password;
            this.StrLink = StrLink;
            this.StrDescription = StrDescription;
            this.SMSSender = SMSSender;
            this.SMSReceiver = SMSReceiver;
            this.OperatorName = OperatorName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendWapPush_WithDLRWithOperatorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendWapPush_WithDLRWithOperator1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendWapPush_WithDLRWithOperatorResult;
        
        public SendWapPush_WithDLRWithOperator1() {
        }
        
        public SendWapPush_WithDLRWithOperator1(int SendWapPush_WithDLRWithOperatorResult) {
            this.SendWapPush_WithDLRWithOperatorResult = SendWapPush_WithDLRWithOperatorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS_WithDLRWithOperator", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMS_WithDLRWithOperator {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SMSText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string SMSLang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string SMSSender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string SMSReceiver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public BrokerDLL.SMSServiceReference.Operators OperatorName;
        
        public SendSMS_WithDLRWithOperator() {
        }
        
        public SendSMS_WithDLRWithOperator(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            this.UserName = UserName;
            this.Password = Password;
            this.SMSText = SMSText;
            this.SMSLang = SMSLang;
            this.SMSSender = SMSSender;
            this.SMSReceiver = SMSReceiver;
            this.OperatorName = OperatorName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS_WithDLRWithOperatorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMS_WithDLRWithOperator1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendSMS_WithDLRWithOperatorResult;
        
        public SendSMS_WithDLRWithOperator1() {
        }
        
        public SendSMS_WithDLRWithOperator1(int SendSMS_WithDLRWithOperatorResult) {
            this.SendSMS_WithDLRWithOperatorResult = SendSMS_WithDLRWithOperatorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendOneSMSToMany_WithDLRWithOperator", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendOneSMSToMany_WithDLRWithOperator {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SMSText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string SMSLang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string SMSSender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string SMSReceiver;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public BrokerDLL.SMSServiceReference.Operators OperatorName;
        
        public SendOneSMSToMany_WithDLRWithOperator() {
        }
        
        public SendOneSMSToMany_WithDLRWithOperator(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            this.UserName = UserName;
            this.Password = Password;
            this.SMSText = SMSText;
            this.SMSLang = SMSLang;
            this.SMSSender = SMSSender;
            this.SMSReceiver = SMSReceiver;
            this.OperatorName = OperatorName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendOneSMSToMany_WithDLRWithOperatorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendOneSMSToMany_WithDLRWithOperator1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object[] SendOneSMSToMany_WithDLRWithOperatorResult;
        
        public SendOneSMSToMany_WithDLRWithOperator1() {
        }
        
        public SendOneSMSToMany_WithDLRWithOperator1(object[] SendOneSMSToMany_WithDLRWithOperatorResult) {
            this.SendOneSMSToMany_WithDLRWithOperatorResult = SendOneSMSToMany_WithDLRWithOperatorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : BrokerDLL.SMSServiceReference.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BrokerDLL.SMSServiceReference.ServiceSoap>, BrokerDLL.SMSServiceReference.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SendFailedSSMS(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver) {
            return base.Channel.SendFailedSSMS(UserName, Password, SMSText, SMSLang, SMSSender, SMSReceiver);
        }
        
        public int SendFailedWapPush(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver) {
            return base.Channel.SendFailedWapPush(UserName, Password, StrLink, StrDescription, SMSSender, SMSReceiver);
        }
        
        public int SendSMS(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver) {
            return base.Channel.SendSMS(UserName, Password, SMSText, SMSLang, SMSSender, SMSReceiver);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BrokerDLL.SMSServiceReference.SendSMSWithOperator1 BrokerDLL.SMSServiceReference.ServiceSoap.SendSMS1(BrokerDLL.SMSServiceReference.SendSMSWithOperator request) {
            return base.Channel.SendSMS1(request);
        }
        
        public int SendSMS1(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            BrokerDLL.SMSServiceReference.SendSMSWithOperator inValue = new BrokerDLL.SMSServiceReference.SendSMSWithOperator();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.SMSText = SMSText;
            inValue.SMSLang = SMSLang;
            inValue.SMSSender = SMSSender;
            inValue.SMSReceiver = SMSReceiver;
            inValue.OperatorName = OperatorName;
            BrokerDLL.SMSServiceReference.SendSMSWithOperator1 retVal = ((BrokerDLL.SMSServiceReference.ServiceSoap)(this)).SendSMS1(inValue);
            return retVal.SendSMSWithOperatorResult;
        }
        
        public object[] SendOneSMSToMany(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver) {
            return base.Channel.SendOneSMSToMany(UserName, Password, SMSText, SMSLang, SMSSender, SMSReceiver);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BrokerDLL.SMSServiceReference.SendOneSMSToManyWithOperator1 BrokerDLL.SMSServiceReference.ServiceSoap.SendOneSMSToMany1(BrokerDLL.SMSServiceReference.SendOneSMSToManyWithOperator request) {
            return base.Channel.SendOneSMSToMany1(request);
        }
        
        public object[] SendOneSMSToMany1(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            BrokerDLL.SMSServiceReference.SendOneSMSToManyWithOperator inValue = new BrokerDLL.SMSServiceReference.SendOneSMSToManyWithOperator();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.SMSText = SMSText;
            inValue.SMSLang = SMSLang;
            inValue.SMSSender = SMSSender;
            inValue.SMSReceiver = SMSReceiver;
            inValue.OperatorName = OperatorName;
            BrokerDLL.SMSServiceReference.SendOneSMSToManyWithOperator1 retVal = ((BrokerDLL.SMSServiceReference.ServiceSoap)(this)).SendOneSMSToMany1(inValue);
            return retVal.SendOneSMSToManyWithOperatorResult;
        }
        
        public int CheckCredit(string username, string password) {
            return base.Channel.CheckCredit(username, password);
        }
        
        public int SendWapPush(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver) {
            return base.Channel.SendWapPush(UserName, Password, StrLink, StrDescription, SMSSender, SMSReceiver);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BrokerDLL.SMSServiceReference.SendWapPushWithOperator1 BrokerDLL.SMSServiceReference.ServiceSoap.SendWapPush1(BrokerDLL.SMSServiceReference.SendWapPushWithOperator request) {
            return base.Channel.SendWapPush1(request);
        }
        
        public int SendWapPush1(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            BrokerDLL.SMSServiceReference.SendWapPushWithOperator inValue = new BrokerDLL.SMSServiceReference.SendWapPushWithOperator();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.StrLink = StrLink;
            inValue.StrDescription = StrDescription;
            inValue.SMSSender = SMSSender;
            inValue.SMSReceiver = SMSReceiver;
            inValue.OperatorName = OperatorName;
            BrokerDLL.SMSServiceReference.SendWapPushWithOperator1 retVal = ((BrokerDLL.SMSServiceReference.ServiceSoap)(this)).SendWapPush1(inValue);
            return retVal.SendWapPushWithOperatorResult;
        }
        
        public object[] SendOneWAPPushToMany_WithDLR(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver) {
            return base.Channel.SendOneWAPPushToMany_WithDLR(UserName, Password, StrLink, StrDescription, SMSSender, SMSReceiver);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BrokerDLL.SMSServiceReference.SendOneWAPPushToMany_WithDLRWithOperator1 BrokerDLL.SMSServiceReference.ServiceSoap.SendOneWAPPushToMany_WithDLR1(BrokerDLL.SMSServiceReference.SendOneWAPPushToMany_WithDLRWithOperator request) {
            return base.Channel.SendOneWAPPushToMany_WithDLR1(request);
        }
        
        public object[] SendOneWAPPushToMany_WithDLR1(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            BrokerDLL.SMSServiceReference.SendOneWAPPushToMany_WithDLRWithOperator inValue = new BrokerDLL.SMSServiceReference.SendOneWAPPushToMany_WithDLRWithOperator();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.StrLink = StrLink;
            inValue.StrDescription = StrDescription;
            inValue.SMSSender = SMSSender;
            inValue.SMSReceiver = SMSReceiver;
            inValue.OperatorName = OperatorName;
            BrokerDLL.SMSServiceReference.SendOneWAPPushToMany_WithDLRWithOperator1 retVal = ((BrokerDLL.SMSServiceReference.ServiceSoap)(this)).SendOneWAPPushToMany_WithDLR1(inValue);
            return retVal.SendOneWAPPushToMany_WithDLRWithOperatorResult;
        }
        
        public object[] SendOneWAPPushToMany(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver) {
            return base.Channel.SendOneWAPPushToMany(UserName, Password, StrLink, StrDescription, SMSSender, SMSReceiver);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BrokerDLL.SMSServiceReference.SendOneWAPPushToManyWithOperator1 BrokerDLL.SMSServiceReference.ServiceSoap.SendOneWAPPushToMany1(BrokerDLL.SMSServiceReference.SendOneWAPPushToManyWithOperator request) {
            return base.Channel.SendOneWAPPushToMany1(request);
        }
        
        public object[] SendOneWAPPushToMany1(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            BrokerDLL.SMSServiceReference.SendOneWAPPushToManyWithOperator inValue = new BrokerDLL.SMSServiceReference.SendOneWAPPushToManyWithOperator();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.StrLink = StrLink;
            inValue.StrDescription = StrDescription;
            inValue.SMSSender = SMSSender;
            inValue.SMSReceiver = SMSReceiver;
            inValue.OperatorName = OperatorName;
            BrokerDLL.SMSServiceReference.SendOneWAPPushToManyWithOperator1 retVal = ((BrokerDLL.SMSServiceReference.ServiceSoap)(this)).SendOneWAPPushToMany1(inValue);
            return retVal.SendOneWAPPushToManyWithOperatorResult;
        }
        
        public int SendSMS_WithDLR(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver) {
            return base.Channel.SendSMS_WithDLR(UserName, Password, SMSText, SMSLang, SMSSender, SMSReceiver);
        }
        
        public int SendSMSWithDLR(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver) {
            return base.Channel.SendSMSWithDLR(UserName, Password, SMSText, SMSLang, SMSSender, SMSReceiver);
        }
        
        public int SendWapPush_WithDLR(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver) {
            return base.Channel.SendWapPush_WithDLR(UserName, Password, StrLink, StrDescription, SMSSender, SMSReceiver);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BrokerDLL.SMSServiceReference.SendWapPush_WithDLRWithOperator1 BrokerDLL.SMSServiceReference.ServiceSoap.SendWapPush_WithDLR1(BrokerDLL.SMSServiceReference.SendWapPush_WithDLRWithOperator request) {
            return base.Channel.SendWapPush_WithDLR1(request);
        }
        
        public int SendWapPush_WithDLR1(string UserName, string Password, string StrLink, string StrDescription, string SMSSender, string SMSReceiver, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            BrokerDLL.SMSServiceReference.SendWapPush_WithDLRWithOperator inValue = new BrokerDLL.SMSServiceReference.SendWapPush_WithDLRWithOperator();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.StrLink = StrLink;
            inValue.StrDescription = StrDescription;
            inValue.SMSSender = SMSSender;
            inValue.SMSReceiver = SMSReceiver;
            inValue.OperatorName = OperatorName;
            BrokerDLL.SMSServiceReference.SendWapPush_WithDLRWithOperator1 retVal = ((BrokerDLL.SMSServiceReference.ServiceSoap)(this)).SendWapPush_WithDLR1(inValue);
            return retVal.SendWapPush_WithDLRWithOperatorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BrokerDLL.SMSServiceReference.SendSMS_WithDLRWithOperator1 BrokerDLL.SMSServiceReference.ServiceSoap.SendSMS_WithDLR1(BrokerDLL.SMSServiceReference.SendSMS_WithDLRWithOperator request) {
            return base.Channel.SendSMS_WithDLR1(request);
        }
        
        public int SendSMS_WithDLR1(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            BrokerDLL.SMSServiceReference.SendSMS_WithDLRWithOperator inValue = new BrokerDLL.SMSServiceReference.SendSMS_WithDLRWithOperator();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.SMSText = SMSText;
            inValue.SMSLang = SMSLang;
            inValue.SMSSender = SMSSender;
            inValue.SMSReceiver = SMSReceiver;
            inValue.OperatorName = OperatorName;
            BrokerDLL.SMSServiceReference.SendSMS_WithDLRWithOperator1 retVal = ((BrokerDLL.SMSServiceReference.ServiceSoap)(this)).SendSMS_WithDLR1(inValue);
            return retVal.SendSMS_WithDLRWithOperatorResult;
        }
        
        public object[] SendManySMS_WithDLR(System.Data.DataSet DS) {
            return base.Channel.SendManySMS_WithDLR(DS);
        }
        
        public object[] SendManyWAPPush_WithDLR(System.Data.DataSet ds) {
            return base.Channel.SendManyWAPPush_WithDLR(ds);
        }
        
        public object[] SendOneSMSToMany_WithDLR(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver) {
            return base.Channel.SendOneSMSToMany_WithDLR(UserName, Password, SMSText, SMSLang, SMSSender, SMSReceiver);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BrokerDLL.SMSServiceReference.SendOneSMSToMany_WithDLRWithOperator1 BrokerDLL.SMSServiceReference.ServiceSoap.SendOneSMSToMany_WithDLR1(BrokerDLL.SMSServiceReference.SendOneSMSToMany_WithDLRWithOperator request) {
            return base.Channel.SendOneSMSToMany_WithDLR1(request);
        }
        
        public object[] SendOneSMSToMany_WithDLR1(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            BrokerDLL.SMSServiceReference.SendOneSMSToMany_WithDLRWithOperator inValue = new BrokerDLL.SMSServiceReference.SendOneSMSToMany_WithDLRWithOperator();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.SMSText = SMSText;
            inValue.SMSLang = SMSLang;
            inValue.SMSSender = SMSSender;
            inValue.SMSReceiver = SMSReceiver;
            inValue.OperatorName = OperatorName;
            BrokerDLL.SMSServiceReference.SendOneSMSToMany_WithDLRWithOperator1 retVal = ((BrokerDLL.SMSServiceReference.ServiceSoap)(this)).SendOneSMSToMany_WithDLR1(inValue);
            return retVal.SendOneSMSToMany_WithDLRWithOperatorResult;
        }
        
        public int SendUnicodeMsgs_WithDLR(string UserName, string Password, string SMSSender, string SMSReceiver, string DCS, string Data) {
            return base.Channel.SendUnicodeMsgs_WithDLR(UserName, Password, SMSSender, SMSReceiver, DCS, Data);
        }
        
        public int SendUnicodeMsgs(string UserName, string Password, string SMSSender, string SMSReceiver, string DCS, string Data) {
            return base.Channel.SendUnicodeMsgs(UserName, Password, SMSSender, SMSReceiver, DCS, Data);
        }
        
        public int SendUnicodeMsgsWithOperator(string UserName, string Password, string SMSSender, string SMSReceiver, string DCS, string Data, BrokerDLL.SMSServiceReference.Operators OperatorName) {
            return base.Channel.SendUnicodeMsgsWithOperator(UserName, Password, SMSSender, SMSReceiver, DCS, Data, OperatorName);
        }
    }
}
