//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Data.Entity.Core.Objects.DataClasses;

[assembly: EdmSchemaAttribute()]

namespace BrokerDLL.Migration
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MigratedRealEstatesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MigratedRealEstatesEntities object using the connection string found in the 'MigratedRealEstatesEntities' section of the application configuration file.
        /// </summary>
        public MigratedRealEstatesEntities() : base("name=MigratedRealEstatesEntities", "MigratedRealEstatesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MigratedRealEstatesEntities object.
        /// </summary>
        public MigratedRealEstatesEntities(string connectionString) : base(connectionString, "MigratedRealEstatesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MigratedRealEstatesEntities object.
        /// </summary>
        public MigratedRealEstatesEntities(EntityConnection connection) : base(connection, "MigratedRealEstatesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BrokerRealEstatesSchema> BrokerRealEstatesSchema
        {
            get
            {
                if ((_BrokerRealEstatesSchema == null))
                {
                    _BrokerRealEstatesSchema = base.CreateObjectSet<BrokerRealEstatesSchema>("BrokerRealEstatesSchema");
                }
                return _BrokerRealEstatesSchema;
            }
        }
        private ObjectSet<BrokerRealEstatesSchema> _BrokerRealEstatesSchema;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PropertyFinderRealEstatesSchema> PropertyFinderRealEstatesSchema
        {
            get
            {
                if ((_PropertyFinderRealEstatesSchema == null))
                {
                    _PropertyFinderRealEstatesSchema = base.CreateObjectSet<PropertyFinderRealEstatesSchema>("PropertyFinderRealEstatesSchema");
                }
                return _PropertyFinderRealEstatesSchema;
            }
        }
        private ObjectSet<PropertyFinderRealEstatesSchema> _PropertyFinderRealEstatesSchema;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<City> City
        {
            get
            {
                if ((_City == null))
                {
                    _City = base.CreateObjectSet<City>("City");
                }
                return _City;
            }
        }
        private ObjectSet<City> _City;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<District> District
        {
            get
            {
                if ((_District == null))
                {
                    _District = base.CreateObjectSet<District>("District");
                }
                return _District;
            }
        }
        private ObjectSet<District> _District;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Types> Types
        {
            get
            {
                if ((_Types == null))
                {
                    _Types = base.CreateObjectSet<Types>("Types");
                }
                return _Types;
            }
        }
        private ObjectSet<Types> _Types;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BrokerRealEstatesSchema EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBrokerRealEstatesSchema(BrokerRealEstatesSchema brokerRealEstatesSchema)
        {
            base.AddObject("BrokerRealEstatesSchema", brokerRealEstatesSchema);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PropertyFinderRealEstatesSchema EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPropertyFinderRealEstatesSchema(PropertyFinderRealEstatesSchema propertyFinderRealEstatesSchema)
        {
            base.AddObject("PropertyFinderRealEstatesSchema", propertyFinderRealEstatesSchema);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the City EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCity(City city)
        {
            base.AddObject("City", city);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the District EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDistrict(District district)
        {
            base.AddObject("District", district);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Types EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTypes(Types types)
        {
            base.AddObject("Types", types);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MigratedRealEstatesModel", Name="BrokerRealEstatesSchema")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BrokerRealEstatesSchema : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BrokerRealEstatesSchema object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static BrokerRealEstatesSchema CreateBrokerRealEstatesSchema(global::System.Int32 id)
        {
            BrokerRealEstatesSchema brokerRealEstatesSchema = new BrokerRealEstatesSchema();
            brokerRealEstatesSchema.ID = id;
            return brokerRealEstatesSchema;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String saleType
        {
            get
            {
                return _saleType;
            }
            set
            {
                OnsaleTypeChanging(value);
                ReportPropertyChanging("saleType");
                _saleType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("saleType");
                OnsaleTypeChanged();
            }
        }
        private global::System.String _saleType;
        partial void OnsaleTypeChanging(global::System.String value);
        partial void OnsaleTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String category
        {
            get
            {
                return _category;
            }
            set
            {
                OncategoryChanging(value);
                ReportPropertyChanging("category");
                _category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("category");
                OncategoryChanged();
            }
        }
        private global::System.String _category;
        partial void OncategoryChanging(global::System.String value);
        partial void OncategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String District
        {
            get
            {
                return _District;
            }
            set
            {
                OnDistrictChanging(value);
                ReportPropertyChanging("District");
                _District = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("District");
                OnDistrictChanged();
            }
        }
        private global::System.String _District;
        partial void OnDistrictChanging(global::System.String value);
        partial void OnDistrictChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.String _Longitude;
        partial void OnLongitudeChanging(global::System.String value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.String _Latitude;
        partial void OnLatitudeChanging(global::System.String value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Area
        {
            get
            {
                return _Area;
            }
            set
            {
                OnAreaChanging(value);
                ReportPropertyChanging("Area");
                _Area = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Area");
                OnAreaChanged();
            }
        }
        private global::System.String _Area;
        partial void OnAreaChanging(global::System.String value);
        partial void OnAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Currency
        {
            get
            {
                return _Currency;
            }
            set
            {
                OnCurrencyChanging(value);
                ReportPropertyChanging("Currency");
                _Currency = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Currency");
                OnCurrencyChanged();
            }
        }
        private global::System.String _Currency;
        partial void OnCurrencyChanging(global::System.String value);
        partial void OnCurrencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String paymenttype
        {
            get
            {
                return _paymenttype;
            }
            set
            {
                OnpaymenttypeChanging(value);
                ReportPropertyChanging("paymenttype");
                _paymenttype = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("paymenttype");
                OnpaymenttypeChanged();
            }
        }
        private global::System.String _paymenttype;
        partial void OnpaymenttypeChanging(global::System.String value);
        partial void OnpaymenttypeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MigratedRealEstatesModel", Name="City")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class City : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new City object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static City CreateCity(global::System.Int32 id)
        {
            City city = new City();
            city.ID = id;
            return city;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private Nullable<global::System.Int32> _Code;
        partial void OnCodeChanging(Nullable<global::System.Int32> value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ar_Name
        {
            get
            {
                return _Ar_Name;
            }
            set
            {
                OnAr_NameChanging(value);
                ReportPropertyChanging("Ar_Name");
                _Ar_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ar_Name");
                OnAr_NameChanged();
            }
        }
        private global::System.String _Ar_Name;
        partial void OnAr_NameChanging(global::System.String value);
        partial void OnAr_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String En_Name
        {
            get
            {
                return _En_Name;
            }
            set
            {
                OnEn_NameChanging(value);
                ReportPropertyChanging("En_Name");
                _En_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("En_Name");
                OnEn_NameChanged();
            }
        }
        private global::System.String _En_Name;
        partial void OnEn_NameChanging(global::System.String value);
        partial void OnEn_NameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MigratedRealEstatesModel", Name="District")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class District : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new District object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static District CreateDistrict(global::System.Int32 id)
        {
            District district = new District();
            district.ID = id;
            return district;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CountryID
        {
            get
            {
                return _CountryID;
            }
            set
            {
                OnCountryIDChanging(value);
                ReportPropertyChanging("CountryID");
                _CountryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CountryID");
                OnCountryIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CountryID;
        partial void OnCountryIDChanging(Nullable<global::System.Int32> value);
        partial void OnCountryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CityID
        {
            get
            {
                return _CityID;
            }
            set
            {
                OnCityIDChanging(value);
                ReportPropertyChanging("CityID");
                _CityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CityID");
                OnCityIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CityID;
        partial void OnCityIDChanging(Nullable<global::System.Int32> value);
        partial void OnCityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private Nullable<global::System.Int32> _Code;
        partial void OnCodeChanging(Nullable<global::System.Int32> value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ar_Name
        {
            get
            {
                return _Ar_Name;
            }
            set
            {
                OnAr_NameChanging(value);
                ReportPropertyChanging("Ar_Name");
                _Ar_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ar_Name");
                OnAr_NameChanged();
            }
        }
        private global::System.String _Ar_Name;
        partial void OnAr_NameChanging(global::System.String value);
        partial void OnAr_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String En_Name
        {
            get
            {
                return _En_Name;
            }
            set
            {
                OnEn_NameChanging(value);
                ReportPropertyChanging("En_Name");
                _En_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("En_Name");
                OnEn_NameChanged();
            }
        }
        private global::System.String _En_Name;
        partial void OnEn_NameChanging(global::System.String value);
        partial void OnEn_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lat
        {
            get
            {
                return _Lat;
            }
            set
            {
                OnLatChanging(value);
                ReportPropertyChanging("Lat");
                _Lat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lat");
                OnLatChanged();
            }
        }
        private global::System.String _Lat;
        partial void OnLatChanging(global::System.String value);
        partial void OnLatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lng
        {
            get
            {
                return _Lng;
            }
            set
            {
                OnLngChanging(value);
                ReportPropertyChanging("Lng");
                _Lng = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lng");
                OnLngChanged();
            }
        }
        private global::System.String _Lng;
        partial void OnLngChanging(global::System.String value);
        partial void OnLngChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City_AR_Name
        {
            get
            {
                return _City_AR_Name;
            }
            set
            {
                OnCity_AR_NameChanging(value);
                ReportPropertyChanging("City_AR_Name");
                _City_AR_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City_AR_Name");
                OnCity_AR_NameChanged();
            }
        }
        private global::System.String _City_AR_Name;
        partial void OnCity_AR_NameChanging(global::System.String value);
        partial void OnCity_AR_NameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MigratedRealEstatesModel", Name="PropertyFinderRealEstatesSchema")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PropertyFinderRealEstatesSchema : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PropertyFinderRealEstatesSchema object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static PropertyFinderRealEstatesSchema CreatePropertyFinderRealEstatesSchema(global::System.Int32 id)
        {
            PropertyFinderRealEstatesSchema propertyFinderRealEstatesSchema = new PropertyFinderRealEstatesSchema();
            propertyFinderRealEstatesSchema.ID = id;
            return propertyFinderRealEstatesSchema;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.String _price;
        partial void OnpriceChanging(global::System.String value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String category
        {
            get
            {
                return _category;
            }
            set
            {
                OncategoryChanging(value);
                ReportPropertyChanging("category");
                _category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("category");
                OncategoryChanged();
            }
        }
        private global::System.String _category;
        partial void OncategoryChanging(global::System.String value);
        partial void OncategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city_province
        {
            get
            {
                return _city_province;
            }
            set
            {
                Oncity_provinceChanging(value);
                ReportPropertyChanging("city_province");
                _city_province = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city_province");
                Oncity_provinceChanged();
            }
        }
        private global::System.String _city_province;
        partial void Oncity_provinceChanging(global::System.String value);
        partial void Oncity_provinceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String town_area
        {
            get
            {
                return _town_area;
            }
            set
            {
                Ontown_areaChanging(value);
                ReportPropertyChanging("town_area");
                _town_area = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("town_area");
                Ontown_areaChanged();
            }
        }
        private global::System.String _town_area;
        partial void Ontown_areaChanging(global::System.String value);
        partial void Ontown_areaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String district
        {
            get
            {
                return _district;
            }
            set
            {
                OndistrictChanging(value);
                ReportPropertyChanging("district");
                _district = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("district");
                OndistrictChanged();
            }
        }
        private global::System.String _district;
        partial void OndistrictChanging(global::System.String value);
        partial void OndistrictChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title_ar
        {
            get
            {
                return _title_ar;
            }
            set
            {
                Ontitle_arChanging(value);
                ReportPropertyChanging("title_ar");
                _title_ar = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title_ar");
                Ontitle_arChanged();
            }
        }
        private global::System.String _title_ar;
        partial void Ontitle_arChanging(global::System.String value);
        partial void Ontitle_arChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description_ar
        {
            get
            {
                return _description_ar;
            }
            set
            {
                Ondescription_arChanging(value);
                ReportPropertyChanging("description_ar");
                _description_ar = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description_ar");
                Ondescription_arChanged();
            }
        }
        private global::System.String _description_ar;
        partial void Ondescription_arChanging(global::System.String value);
        partial void Ondescription_arChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sqm
        {
            get
            {
                return _sqm;
            }
            set
            {
                OnsqmChanging(value);
                ReportPropertyChanging("sqm");
                _sqm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sqm");
                OnsqmChanged();
            }
        }
        private Nullable<global::System.Int32> _sqm;
        partial void OnsqmChanging(Nullable<global::System.Int32> value);
        partial void OnsqmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bedroom
        {
            get
            {
                return _bedroom;
            }
            set
            {
                OnbedroomChanging(value);
                ReportPropertyChanging("bedroom");
                _bedroom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bedroom");
                OnbedroomChanged();
            }
        }
        private Nullable<global::System.Int32> _bedroom;
        partial void OnbedroomChanging(Nullable<global::System.Int32> value);
        partial void OnbedroomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bathroom
        {
            get
            {
                return _bathroom;
            }
            set
            {
                OnbathroomChanging(value);
                ReportPropertyChanging("bathroom");
                _bathroom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bathroom");
                OnbathroomChanged();
            }
        }
        private Nullable<global::System.Int32> _bathroom;
        partial void OnbathroomChanging(Nullable<global::System.Int32> value);
        partial void OnbathroomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agent_name
        {
            get
            {
                return _agent_name;
            }
            set
            {
                Onagent_nameChanging(value);
                ReportPropertyChanging("agent_name");
                _agent_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agent_name");
                Onagent_nameChanged();
            }
        }
        private global::System.String _agent_name;
        partial void Onagent_nameChanging(global::System.String value);
        partial void Onagent_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agent_email
        {
            get
            {
                return _agent_email;
            }
            set
            {
                Onagent_emailChanging(value);
                ReportPropertyChanging("agent_email");
                _agent_email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agent_email");
                Onagent_emailChanged();
            }
        }
        private global::System.String _agent_email;
        partial void Onagent_emailChanging(global::System.String value);
        partial void Onagent_emailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agent_number
        {
            get
            {
                return _agent_number;
            }
            set
            {
                Onagent_numberChanging(value);
                ReportPropertyChanging("agent_number");
                _agent_number = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agent_number");
                Onagent_numberChanged();
            }
        }
        private global::System.String _agent_number;
        partial void Onagent_numberChanging(global::System.String value);
        partial void Onagent_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String photo_url_1
        {
            get
            {
                return _photo_url_1;
            }
            set
            {
                Onphoto_url_1Changing(value);
                ReportPropertyChanging("photo_url_1");
                _photo_url_1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("photo_url_1");
                Onphoto_url_1Changed();
            }
        }
        private global::System.String _photo_url_1;
        partial void Onphoto_url_1Changing(global::System.String value);
        partial void Onphoto_url_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String photo_url_2
        {
            get
            {
                return _photo_url_2;
            }
            set
            {
                Onphoto_url_2Changing(value);
                ReportPropertyChanging("photo_url_2");
                _photo_url_2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("photo_url_2");
                Onphoto_url_2Changed();
            }
        }
        private global::System.String _photo_url_2;
        partial void Onphoto_url_2Changing(global::System.String value);
        partial void Onphoto_url_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String photo_url_3
        {
            get
            {
                return _photo_url_3;
            }
            set
            {
                Onphoto_url_3Changing(value);
                ReportPropertyChanging("photo_url_3");
                _photo_url_3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("photo_url_3");
                Onphoto_url_3Changed();
            }
        }
        private global::System.String _photo_url_3;
        partial void Onphoto_url_3Changing(global::System.String value);
        partial void Onphoto_url_3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String photo_url_4
        {
            get
            {
                return _photo_url_4;
            }
            set
            {
                Onphoto_url_4Changing(value);
                ReportPropertyChanging("photo_url_4");
                _photo_url_4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("photo_url_4");
                Onphoto_url_4Changed();
            }
        }
        private global::System.String _photo_url_4;
        partial void Onphoto_url_4Changing(global::System.String value);
        partial void Onphoto_url_4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String photo_url_5
        {
            get
            {
                return _photo_url_5;
            }
            set
            {
                Onphoto_url_5Changing(value);
                ReportPropertyChanging("photo_url_5");
                _photo_url_5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("photo_url_5");
                Onphoto_url_5Changed();
            }
        }
        private global::System.String _photo_url_5;
        partial void Onphoto_url_5Changing(global::System.String value);
        partial void Onphoto_url_5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String photo_url_6
        {
            get
            {
                return _photo_url_6;
            }
            set
            {
                Onphoto_url_6Changing(value);
                ReportPropertyChanging("photo_url_6");
                _photo_url_6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("photo_url_6");
                Onphoto_url_6Changed();
            }
        }
        private global::System.String _photo_url_6;
        partial void Onphoto_url_6Changing(global::System.String value);
        partial void Onphoto_url_6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String photo_url_7
        {
            get
            {
                return _photo_url_7;
            }
            set
            {
                Onphoto_url_7Changing(value);
                ReportPropertyChanging("photo_url_7");
                _photo_url_7 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("photo_url_7");
                Onphoto_url_7Changed();
            }
        }
        private global::System.String _photo_url_7;
        partial void Onphoto_url_7Changing(global::System.String value);
        partial void Onphoto_url_7Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String photo_url_8
        {
            get
            {
                return _photo_url_8;
            }
            set
            {
                Onphoto_url_8Changing(value);
                ReportPropertyChanging("photo_url_8");
                _photo_url_8 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("photo_url_8");
                Onphoto_url_8Changed();
            }
        }
        private global::System.String _photo_url_8;
        partial void Onphoto_url_8Changing(global::System.String value);
        partial void Onphoto_url_8Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String photo_url_9
        {
            get
            {
                return _photo_url_9;
            }
            set
            {
                Onphoto_url_9Changing(value);
                ReportPropertyChanging("photo_url_9");
                _photo_url_9 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("photo_url_9");
                Onphoto_url_9Changed();
            }
        }
        private global::System.String _photo_url_9;
        partial void Onphoto_url_9Changing(global::System.String value);
        partial void Onphoto_url_9Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String photo_url_10
        {
            get
            {
                return _photo_url_10;
            }
            set
            {
                Onphoto_url_10Changing(value);
                ReportPropertyChanging("photo_url_10");
                _photo_url_10 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("photo_url_10");
                Onphoto_url_10Changed();
            }
        }
        private global::System.String _photo_url_10;
        partial void Onphoto_url_10Changing(global::System.String value);
        partial void Onphoto_url_10Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SaleType
        {
            get
            {
                return _SaleType;
            }
            set
            {
                OnSaleTypeChanging(value);
                ReportPropertyChanging("SaleType");
                _SaleType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SaleType");
                OnSaleTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _SaleType;
        partial void OnSaleTypeChanging(Nullable<global::System.Int32> value);
        partial void OnSaleTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoomCriteriaID
        {
            get
            {
                return _RoomCriteriaID;
            }
            set
            {
                OnRoomCriteriaIDChanging(value);
                ReportPropertyChanging("RoomCriteriaID");
                _RoomCriteriaID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoomCriteriaID");
                OnRoomCriteriaIDChanged();
            }
        }
        private Nullable<global::System.Int32> _RoomCriteriaID;
        partial void OnRoomCriteriaIDChanging(Nullable<global::System.Int32> value);
        partial void OnRoomCriteriaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BathroomCriteriaID
        {
            get
            {
                return _BathroomCriteriaID;
            }
            set
            {
                OnBathroomCriteriaIDChanging(value);
                ReportPropertyChanging("BathroomCriteriaID");
                _BathroomCriteriaID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BathroomCriteriaID");
                OnBathroomCriteriaIDChanged();
            }
        }
        private Nullable<global::System.Int32> _BathroomCriteriaID;
        partial void OnBathroomCriteriaIDChanging(Nullable<global::System.Int32> value);
        partial void OnBathroomCriteriaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TypeID
        {
            get
            {
                return _TypeID;
            }
            set
            {
                OnTypeIDChanging(value);
                ReportPropertyChanging("TypeID");
                _TypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TypeID");
                OnTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TypeID;
        partial void OnTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DistrictID
        {
            get
            {
                return _DistrictID;
            }
            set
            {
                OnDistrictIDChanging(value);
                ReportPropertyChanging("DistrictID");
                _DistrictID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DistrictID");
                OnDistrictIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DistrictID;
        partial void OnDistrictIDChanging(Nullable<global::System.Int32> value);
        partial void OnDistrictIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsMigrated
        {
            get
            {
                return _IsMigrated;
            }
            set
            {
                OnIsMigratedChanging(value);
                ReportPropertyChanging("IsMigrated");
                _IsMigrated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMigrated");
                OnIsMigratedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsMigrated;
        partial void OnIsMigratedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsMigratedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MigratedRealEstatesModel", Name="Types")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Types : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Types object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Types CreateTypes(global::System.Int32 id)
        {
            Types types = new Types();
            types.ID = id;
            return types;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private Nullable<global::System.Int32> _Code;
        partial void OnCodeChanging(Nullable<global::System.Int32> value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                OnCategoryIDChanging(value);
                ReportPropertyChanging("CategoryID");
                _CategoryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryID");
                OnCategoryIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CategoryID;
        partial void OnCategoryIDChanging(Nullable<global::System.Int32> value);
        partial void OnCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ar_Name
        {
            get
            {
                return _Ar_Name;
            }
            set
            {
                OnAr_NameChanging(value);
                ReportPropertyChanging("Ar_Name");
                _Ar_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ar_Name");
                OnAr_NameChanged();
            }
        }
        private global::System.String _Ar_Name;
        partial void OnAr_NameChanging(global::System.String value);
        partial void OnAr_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String En_Name
        {
            get
            {
                return _En_Name;
            }
            set
            {
                OnEn_NameChanging(value);
                ReportPropertyChanging("En_Name");
                _En_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("En_Name");
                OnEn_NameChanged();
            }
        }
        private global::System.String _En_Name;
        partial void OnEn_NameChanging(global::System.String value);
        partial void OnEn_NameChanged();

        #endregion
    
    }

    #endregion
    
}
