//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerMVC.SMSServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSServiceReference.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CheckCredit(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckCredit", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CheckCreditAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendSMS(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SendSMSAsync(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSWithDLR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendSMSWithDLR(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSWithDLR", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SendSMSWithDLRAsync(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : BrokerMVC.SMSServiceReference.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BrokerMVC.SMSServiceReference.ServiceSoap>, BrokerMVC.SMSServiceReference.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CheckCredit(string username, string password) {
            return base.Channel.CheckCredit(username, password);
        }
        
        public System.Threading.Tasks.Task<int> CheckCreditAsync(string username, string password) {
            return base.Channel.CheckCreditAsync(username, password);
        }
        
        public int SendSMS(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver) {
            return base.Channel.SendSMS(UserName, Password, SMSText, SMSLang, SMSSender, SMSReceiver);
        }
        
        public System.Threading.Tasks.Task<int> SendSMSAsync(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver) {
            return base.Channel.SendSMSAsync(UserName, Password, SMSText, SMSLang, SMSSender, SMSReceiver);
        }
        
        public int SendSMSWithDLR(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver) {
            return base.Channel.SendSMSWithDLR(UserName, Password, SMSText, SMSLang, SMSSender, SMSReceiver);
        }
        
        public System.Threading.Tasks.Task<int> SendSMSWithDLRAsync(string UserName, string Password, string SMSText, string SMSLang, string SMSSender, string SMSReceiver) {
            return base.Channel.SendSMSWithDLRAsync(UserName, Password, SMSText, SMSLang, SMSSender, SMSReceiver);
        }
    }
}
