//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrokerMVC.ResourcesFiles.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Company.
        /// </summary>
        public static string AboutCompany {
            get {
                return ResourceManager.GetString("AboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Project.
        /// </summary>
        public static string AboutProject {
            get {
                return ResourceManager.GetString("AboutProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Data.
        /// </summary>
        public static string AccountData {
            get {
                return ResourceManager.GetString("AccountData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Type.
        /// </summary>
        public static string ActionType {
            get {
                return ResourceManager.GetString("ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side Ad.
        /// </summary>
        public static string AdContentSideImage {
            get {
                return ResourceManager.GetString("AdContentSideImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement Data.
        /// </summary>
        public static string AdData {
            get {
                return ResourceManager.GetString("AdData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorite.
        /// </summary>
        public static string AddFavorite {
            get {
                return ResourceManager.GetString("AddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Data.
        /// </summary>
        public static string AdditionalData {
            get {
                return ResourceManager.GetString("AdditionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New RealEstate.
        /// </summary>
        public static string AddRealestate {
            get {
                return ResourceManager.GetString("AddRealestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page Main Ad Desktop.
        /// </summary>
        public static string AdHomePageMainLarge {
            get {
                return ResourceManager.GetString("AdHomePageMainLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page Main Ad Mobile.
        /// </summary>
        public static string AdHomePageMainSmall {
            get {
                return ResourceManager.GetString("AdHomePageMainSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page Side Ad.
        /// </summary>
        public static string AdHomePageSide {
            get {
                return ResourceManager.GetString("AdHomePageSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement Title.
        /// </summary>
        public static string AdTitle {
            get {
                return ResourceManager.GetString("AdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisements.
        /// </summary>
        public static string Advertisements {
            get {
                return ResourceManager.GetString("Advertisements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertiser.
        /// </summary>
        public static string Advertiser {
            get {
                return ResourceManager.GetString("Advertiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertiser Data.
        /// </summary>
        public static string AdvertiserData {
            get {
                return ResourceManager.GetString("AdvertiserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqarstock Services.
        /// </summary>
        public static string AqarstockServices {
            get {
                return ResourceManager.GetString("AqarstockServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total available Projects Number.
        /// </summary>
        public static string AvailableProjects {
            get {
                return ResourceManager.GetString("AvailableProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total available users Number.
        /// </summary>
        public static string AvailableUsers {
            get {
                return ResourceManager.GetString("AvailableUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend.
        /// </summary>
        public static string Backend {
            get {
                return ResourceManager.GetString("Backend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Data.
        /// </summary>
        public static string BasicData {
            get {
                return ResourceManager.GetString("BasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you can&apos;t add new project.
        /// </summary>
        public static string CantAddProject {
            get {
                return ResourceManager.GetString("CantAddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you can&apos;t add new company employee.
        /// </summary>
        public static string CantAddUser {
            get {
                return ResourceManager.GetString("CantAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogs Categories.
        /// </summary>
        public static string CatalogCategories {
            get {
                return ResourceManager.GetString("CatalogCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Names.
        /// </summary>
        public static string CatalogsNames {
            get {
                return ResourceManager.GetString("CatalogsNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Role.
        /// </summary>
        public static string ChangeRole {
            get {
                return ResourceManager.GetString("ChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities List.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codes.
        /// </summary>
        public static string Codes {
            get {
                return ResourceManager.GetString("Codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial.
        /// </summary>
        public static string Commercial {
            get {
                return ResourceManager.GetString("Commercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realestate Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Account.
        /// </summary>
        public static string CompanyAccount {
            get {
                return ResourceManager.GetString("CompanyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string CompanyAdmin {
            get {
                return ResourceManager.GetString("CompanyAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Data.
        /// </summary>
        public static string CompanyData {
            get {
                return ResourceManager.GetString("CompanyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Projects.
        /// </summary>
        public static string CompanyProjects {
            get {
                return ResourceManager.GetString("CompanyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Purchase Requests.
        /// </summary>
        public static string CompanyPurchaseRequests {
            get {
                return ResourceManager.GetString("CompanyPurchaseRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Real estates.
        /// </summary>
        public static string CompanyRealestates {
            get {
                return ResourceManager.GetString("CompanyRealestates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare List.
        /// </summary>
        public static string CompareList {
            get {
                return ResourceManager.GetString("CompareList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complains.
        /// </summary>
        public static string Complains {
            get {
                return ResourceManager.GetString("Complains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complain Title.
        /// </summary>
        public static string ComplainTitle {
            get {
                return ResourceManager.GetString("ComplainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Registration.
        /// </summary>
        public static string CompleteRegistration {
            get {
                return ResourceManager.GetString("CompleteRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the terms and conditions.
        /// </summary>
        public static string ConditionAgree {
            get {
                return ResourceManager.GetString("ConditionAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Data.
        /// </summary>
        public static string ContactData {
            get {
                return ResourceManager.GetString("ContactData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries List.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        public static string Criteria {
            get {
                return ResourceManager.GetString("Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies List.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Projects Number.
        /// </summary>
        public static string CurrentProjects {
            get {
                return ResourceManager.GetString("CurrentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User Numbers.
        /// </summary>
        public static string CurrentUsers {
            get {
                return ResourceManager.GetString("CurrentUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Inquiries.
        /// </summary>
        public static string CustomerInquiries {
            get {
                return ResourceManager.GetString("CustomerInquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers of New Customer Inquiries.
        /// </summary>
        public static string CustomerInquiriesNo {
            get {
                return ResourceManager.GetString("CustomerInquiriesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashBoard.
        /// </summary>
        public static string DashBoard {
            get {
                return ResourceManager.GetString("DashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default image.
        /// </summary>
        public static string DefaultImage {
            get {
                return ResourceManager.GetString("DefaultImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Vr.
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string Districts {
            get {
                return ResourceManager.GetString("Districts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downgrade Subscription to Employee.
        /// </summary>
        public static string Downgrade {
            get {
                return ResourceManager.GetString("Downgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Code.
        /// </summary>
        public static string EmbedCode {
            get {
                return ResourceManager.GetString("EmbedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Advertisement Title.
        /// </summary>
        public static string EnAdTitle {
            get {
                return ResourceManager.GetString("EnAdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Description.
        /// </summary>
        public static string EnDescription {
            get {
                return ResourceManager.GetString("EnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slogan in English.
        /// </summary>
        public static string EnSlogan {
            get {
                return ResourceManager.GetString("EnSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Street Name.
        /// </summary>
        public static string EnStreet {
            get {
                return ResourceManager.GetString("EnStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Summary.
        /// </summary>
        public static string EnSummary {
            get {
                return ResourceManager.GetString("EnSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Real estates.
        /// </summary>
        public static string FavouriteRealestates {
            get {
                return ResourceManager.GetString("FavouriteRealestates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string FeaturesData {
            get {
                return ResourceManager.GetString("FeaturesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Data.
        /// </summary>
        public static string FinancialData {
            get {
                return ResourceManager.GetString("FinancialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password.
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Rent.
        /// </summary>
        public static string ForRent {
            get {
                return ResourceManager.GetString("ForRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Link.
        /// </summary>
        public static string GeneralLink {
            get {
                return ResourceManager.GetString("GeneralLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Catalogs.
        /// </summary>
        public static string GenerateCatalogs {
            get {
                return ResourceManager.GetString("GenerateCatalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, .
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Realestate.
        /// </summary>
        public static string InCompleteRealestate {
            get {
                return ResourceManager.GetString("InCompleteRealestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquire About.
        /// </summary>
        public static string InqueryAbout {
            get {
                return ResourceManager.GetString("InqueryAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string keyword {
            get {
                return ResourceManager.GetString("keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keyword Link.
        /// </summary>
        public static string KeywordLink {
            get {
                return ResourceManager.GetString("KeywordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lands.
        /// </summary>
        public static string Lands {
            get {
                return ResourceManager.GetString("Lands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Added.
        /// </summary>
        public static string LatestAdded {
            get {
                return ResourceManager.GetString("LatestAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Rent Properties.
        /// </summary>
        public static string LatestAddedForRent {
            get {
                return ResourceManager.GetString("LatestAddedForRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Sale Properties.
        /// </summary>
        public static string LatestAddedForSale {
            get {
                return ResourceManager.GetString("LatestAddedForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than.
        /// </summary>
        public static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Keyword.
        /// </summary>
        public static string MainKeyWord {
            get {
                return ResourceManager.GetString("MainKeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Messages.
        /// </summary>
        public static string ManagementMessages {
            get {
                return ResourceManager.GetString("ManagementMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markering Srvices.
        /// </summary>
        public static string MarketingServices {
            get {
                return ResourceManager.GetString("MarketingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        public static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Ve.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string Models {
            get {
                return ResourceManager.GetString("Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassign Realestates.
        /// </summary>
        public static string MoveRealestate {
            get {
                return ResourceManager.GetString("MoveRealestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer To.
        /// </summary>
        public static string MoveTo {
            get {
                return ResourceManager.GetString("MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must.
        /// </summary>
        public static string Must {
            get {
                return ResourceManager.GetString("Must", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Projects.
        /// </summary>
        public static string MyProjects {
            get {
                return ResourceManager.GetString("MyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Real Estates.
        /// </summary>
        public static string MyRealestates {
            get {
                return ResourceManager.GetString("MyRealestates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers of New Notifications.
        /// </summary>
        public static string NotificationNos {
            get {
                return ResourceManager.GetString("NotificationNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurance No.
        /// </summary>
        public static string OccuranceNo {
            get {
                return ResourceManager.GetString("OccuranceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Catalogs.
        /// </summary>
        public static string OldCatalogs {
            get {
                return ResourceManager.GetString("OldCatalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Data.
        /// </summary>
        public static string OwnerData {
            get {
                return ResourceManager.GetString("OwnerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqar Stock | real estate search engine | Appartements,Villa or Lands | for sale or rent.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph Headers.
        /// </summary>
        public static string ParagraphHeaders {
            get {
                return ResourceManager.GetString("ParagraphHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph No.
        /// </summary>
        public static string ParagraphNo {
            get {
                return ResourceManager.GetString("ParagraphNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Account.
        /// </summary>
        public static string PersonalAccount {
            get {
                return ResourceManager.GetString("PersonalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precious.
        /// </summary>
        public static string Precious {
            get {
                return ResourceManager.GetString("Precious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Data.
        /// </summary>
        public static string ProjectData {
            get {
                return ResourceManager.GetString("ProjectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string ProjectList {
            get {
                return ResourceManager.GetString("ProjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers of New Purchase requests.
        /// </summary>
        public static string PurchaseRequestNos {
            get {
                return ResourceManager.GetString("PurchaseRequestNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Requests.
        /// </summary>
        public static string PurchaseRequests {
            get {
                return ResourceManager.GetString("PurchaseRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Requests Report.
        /// </summary>
        public static string PurchaseRequestsReport {
            get {
                return ResourceManager.GetString("PurchaseRequestsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real estate.
        /// </summary>
        public static string RealEstate {
            get {
                return ResourceManager.GetString("RealEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealestateCategory.
        /// </summary>
        public static string RealestateCategory {
            get {
                return ResourceManager.GetString("RealestateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realestate Criteria.
        /// </summary>
        public static string RealestateCriteria {
            get {
                return ResourceManager.GetString("RealestateCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Estates.
        /// </summary>
        public static string Realestates {
            get {
                return ResourceManager.GetString("Realestates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realestate Status.
        /// </summary>
        public static string RealestateStatusList {
            get {
                return ResourceManager.GetString("RealestateStatusList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realestate Type.
        /// </summary>
        public static string RealestateType {
            get {
                return ResourceManager.GetString("RealestateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realestate Types List.
        /// </summary>
        public static string RealestateTypes {
            get {
                return ResourceManager.GetString("RealestateTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your data to subscribe to Aqar Stock.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Reply.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Realestates.
        /// </summary>
        public static string RequestedRealestates {
            get {
                return ResourceManager.GetString("RequestedRealestates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resedintial.
        /// </summary>
        public static string Resedintial {
            get {
                return ResourceManager.GetString("Resedintial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend ActivationCode.
        /// </summary>
        public static string ResendCode {
            get {
                return ResourceManager.GetString("ResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real estate Offered for.
        /// </summary>
        public static string SaleType {
            get {
                return ResourceManager.GetString("SaleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search keyword.
        /// </summary>
        public static string SearchKeyword {
            get {
                return ResourceManager.GetString("SearchKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Projects.
        /// </summary>
        public static string SearchProjects {
            get {
                return ResourceManager.GetString("SearchProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Properties.
        /// </summary>
        public static string SearchProperties {
            get {
                return ResourceManager.GetString("SearchProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or send Message.
        /// </summary>
        public static string SendCompanyMessage {
            get {
                return ResourceManager.GetString("SendCompanyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Complain.
        /// </summary>
        public static string SendComplain {
            get {
                return ResourceManager.GetString("SendComplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Signin {
            get {
                return ResourceManager.GetString("Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real estate search engine provides every opportunity to sell and rent apartments, land, villas, duplexes and others .. Easily online for free without an intermediary.
        /// </summary>
        public static string SiteDescription {
            get {
                return ResourceManager.GetString("SiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqar Stock.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slogan.
        /// </summary>
        public static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold.
        /// </summary>
        public static string Sold {
            get {
                return ResourceManager.GetString("Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Offers.
        /// </summary>
        public static string SpecialPropList {
            get {
                return ResourceManager.GetString("SpecialPropList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site Pages Content.
        /// </summary>
        public static string StaticPages {
            get {
                return ResourceManager.GetString("StaticPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber Data.
        /// </summary>
        public static string SubscriberData {
            get {
                return ResourceManager.GetString("SubscriberData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of Real estates.
        /// </summary>
        public static string SubscriberRealestateNo {
            get {
                return ResourceManager.GetString("SubscriberRealestateNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supscription Type.
        /// </summary>
        public static string SupscriptionType {
            get {
                return ResourceManager.GetString("SupscriptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supscripe.
        /// </summary>
        public static string SupscriptionTypes {
            get {
                return ResourceManager.GetString("SupscriptionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        public static string Suspend {
            get {
                return ResourceManager.GetString("Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string Suspended {
            get {
                return ResourceManager.GetString("Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Account Is Suspended.
        /// </summary>
        public static string SuspendedAccount {
            get {
                return ResourceManager.GetString("SuspendedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended Real Estates.
        /// </summary>
        public static string SuspendedRealestates {
            get {
                return ResourceManager.GetString("SuspendedRealestates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend Reason.
        /// </summary>
        public static string SuspendReason {
            get {
                return ResourceManager.GetString("SuspendReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Support.
        /// </summary>
        public static string TechnicalSupport {
            get {
                return ResourceManager.GetString("TechnicalSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Subscription to Administrator.
        /// </summary>
        public static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use My Contact Data.
        /// </summary>
        public static string UseContactData {
            get {
                return ResourceManager.GetString("UseContactData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username, email or mobile number.
        /// </summary>
        public static string UserNameEmailMobilNo {
            get {
                return ResourceManager.GetString("UserNameEmailMobilNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username in English and without spaces .
        /// </summary>
        public static string UserNameForRegister {
            get {
                return ResourceManager.GetString("UserNameForRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Type.
        /// </summary>
        public static string ValueType {
            get {
                return ResourceManager.GetString("ValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Name.
        /// </summary>
        public static string VideoName {
            get {
                return ResourceManager.GetString("VideoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog words No.
        /// </summary>
        public static string WordsNo {
            get {
                return ResourceManager.GetString("WordsNo", resourceCulture);
            }
        }
    }
}
