//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrokerMVC.ResourcesFiles.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Successfully.
        /// </summary>
        public static string ActivatedSuccessfully {
            get {
                return ResourceManager.GetString("ActivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember that the accuracy of the data increases the chances of selling.
        /// </summary>
        public static string AddAditionalDataMsg {
            get {
                return ResourceManager.GetString("AddAditionalDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can&apos;t Compare More than 4 Properties.
        /// </summary>
        public static string AddingCompareFailed {
            get {
                return ResourceManager.GetString("AddingCompareFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Add your contact data.
        /// </summary>
        public static string AddUserDataMsg {
            get {
                return ResourceManager.GetString("AddUserDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment / Villa / Land (type) for sale / for rent [installment / Cash] ( District Name) - (most important areas nearby).
        /// </summary>
        public static string AdPlaceHolder {
            get {
                return ResourceManager.GetString("AdPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write brief title for the advertisement which contains common words used in search on google.
        /// </summary>
        public static string AdTooltip {
            get {
                return ResourceManager.GetString("AdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area is Required.
        /// </summary>
        public static string AreaRequired {
            get {
                return ResourceManager.GetString("AreaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The area in square meters.
        /// </summary>
        public static string AreaToolTip {
            get {
                return ResourceManager.GetString("AreaToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can&apos;t Add More Than.
        /// </summary>
        public static string CantAddMsg {
            get {
                return ResourceManager.GetString("CantAddMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write each name in new line.
        /// </summary>
        public static string CatalogNamesTooltip {
            get {
                return ResourceManager.GetString("CatalogNamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: If you want to sell your property Select Residential.
        /// </summary>
        public static string CategoryTooltip {
            get {
                return ResourceManager.GetString("CategoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code you entered is not match the Activation code.
        /// </summary>
        public static string CodeNotMatch {
            get {
                return ResourceManager.GetString("CodeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A New activation code has been sent to your email and phone.
        /// </summary>
        public static string CodeSentSuccessfuly {
            get {
                return ResourceManager.GetString("CodeSentSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter realestates codes seperated by &apos;,&apos;.
        /// </summary>
        public static string CodesTooltip {
            get {
                return ResourceManager.GetString("CodesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Enter your company data first.
        /// </summary>
        public static string CompanyDataRequired {
            get {
                return ResourceManager.GetString("CompanyDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change subscription into Company Administriator?.
        /// </summary>
        public static string ConfirmChangeSubscription {
            get {
                return ResourceManager.GetString("ConfirmChangeSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm the Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for more information you can contact us .
        /// </summary>
        public static string ContactAdmin {
            get {
                return ResourceManager.GetString("ContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remember that data accuracy will increases your chances of selling or leasing your property.
        /// </summary>
        public static string CreateNewMsg {
            get {
                return ResourceManager.GetString("CreateNewMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data related to the project will be deleted which is:.
        /// </summary>
        public static string DeleteProjectRelatedData {
            get {
                return ResourceManager.GetString("DeleteProjectRelatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data related to the real estate will be deleted which is:.
        /// </summary>
        public static string DeleteRealestateRelatedData {
            get {
                return ResourceManager.GetString("DeleteRealestateRelatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data related to the user will be deleted which is:.
        /// </summary>
        public static string DeleteSubscriberRelatedData {
            get {
                return ResourceManager.GetString("DeleteSubscriberRelatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Description is Required.
        /// </summary>
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Write full description of the property ,its features ,advantages of its location and the available services , such as schools, hospitals and so on - only 500 characters..
        /// </summary>
        public static string DescriptionTooltip {
            get {
                return ResourceManager.GetString("DescriptionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Exist.
        /// </summary>
        public static string EmptyMsg {
            get {
                return ResourceManager.GetString("EmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Description is Required.
        /// </summary>
        public static string EnglishDescriptionRequired {
            get {
                return ResourceManager.GetString("EnglishDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name is Required.
        /// </summary>
        public static string EnglishNameRequired {
            get {
                return ResourceManager.GetString("EnglishNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Slogan is Required.
        /// </summary>
        public static string EnglishSloganRequired {
            get {
                return ResourceManager.GetString("EnglishSloganRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Street Name is Required.
        /// </summary>
        public static string EnglishStreetNameRequired {
            get {
                return ResourceManager.GetString("EnglishStreetNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Summary is Required.
        /// </summary>
        public static string EnSummaryRequired {
            get {
                return ResourceManager.GetString("EnSummaryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or phone number.
        /// </summary>
        public static string ErrorInvalidEmailOrPhoneNumber {
            get {
                return ResourceManager.GetString("ErrorInvalidEmailOrPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mobile number.
        /// </summary>
        public static string ErrorInvalidMobileNo {
            get {
                return ResourceManager.GetString("ErrorInvalidMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        public static string ErrorInvalidUsername {
            get {
                return ResourceManager.GetString("ErrorInvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error has been occurred, Please try again.
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry,.
        /// </summary>
        public static string ErrorTitleMsg {
            get {
                return ResourceManager.GetString("ErrorTitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or phone number already exist.
        /// </summary>
        public static string ErrorUserNameExist {
            get {
                return ResourceManager.GetString("ErrorUserNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or phone number not exist.
        /// </summary>
        public static string ErrorUserNameNotExist {
            get {
                return ResourceManager.GetString("ErrorUserNameNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must log in before you add the property to your favorite properties.
        /// </summary>
        public static string FavoritePropErrorMsg {
            get {
                return ResourceManager.GetString("FavoritePropErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property has been added to your Favorites list.
        /// </summary>
        public static string FavoritePropMsg {
            get {
                return ResourceManager.GetString("FavoritePropMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover password.
        /// </summary>
        public static string ForgetPasswordRecover {
            get {
                return ResourceManager.GetString("ForgetPasswordRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password recovery code has been successfully sent to.
        /// </summary>
        public static string ForgetPasswordRecoverTitle {
            get {
                return ResourceManager.GetString("ForgetPasswordRecoverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery code.
        /// </summary>
        public static string ForgetPasswordTitle {
            get {
                return ResourceManager.GetString("ForgetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been sent to your phone number and e-mail. Please login.
        /// </summary>
        public static string GeneratePasswordMsg {
            get {
                return ResourceManager.GetString("GeneratePasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please write each header in new line.
        /// </summary>
        public static string HeadersTooltip {
            get {
                return ResourceManager.GetString("HeadersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dimensions must be 32*32.
        /// </summary>
        public static string IconToolTip {
            get {
                return ResourceManager.GetString("IconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Please enter The Address.
        /// </summary>
        public static string InCompleteAddress {
            get {
                return ResourceManager.GetString("InCompleteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Data is not Complete.
        /// </summary>
        public static string IncompleteMsg {
            get {
                return ResourceManager.GetString("IncompleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Photos of your RealEstate.
        /// </summary>
        public static string InCompletePhotos {
            get {
                return ResourceManager.GetString("InCompletePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete real estates will not appear on the site.
        /// </summary>
        public static string InCompleteRealestateMsg {
            get {
                return ResourceManager.GetString("InCompleteRealestateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists.
        /// </summary>
        public static string InValidEmail {
            get {
                return ResourceManager.GetString("InValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number already exists.
        /// </summary>
        public static string InValidMobileNo {
            get {
                return ResourceManager.GetString("InValidMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not correct.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists.
        /// </summary>
        public static string InValidUserName {
            get {
                return ResourceManager.GetString("InValidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword is Required.
        /// </summary>
        public static string KeywordRequired {
            get {
                return ResourceManager.GetString("KeywordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude is Required.
        /// </summary>
        public static string LatitudeRequired {
            get {
                return ResourceManager.GetString("LatitudeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dimensions must be 367*367.
        /// </summary>
        public static string LogoToolTip {
            get {
                return ResourceManager.GetString("LogoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude is Required.
        /// </summary>
        public static string LongitudeRequired {
            get {
                return ResourceManager.GetString("LongitudeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select the employee whose the estates will be transferred to him.
        /// </summary>
        public static string MovetoRequired {
            get {
                return ResourceManager.GetString("MovetoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name is Required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Service: send to us your desired real estate features and we will tell you when we find it.
        /// </summary>
        public static string NotifyTitle {
            get {
                return ResourceManager.GetString("NotifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the password confirmation not matched with the password.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the account is not activated yet.
        /// </summary>
        public static string PendingAccount {
            get {
                return ResourceManager.GetString("PendingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account is not activated yet Please Enter The Activation Code.
        /// </summary>
        public static string PendingUserMsg {
            get {
                return ResourceManager.GetString("PendingUserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is Required.
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Photo.
        /// </summary>
        public static string PhotoRequired {
            get {
                return ResourceManager.GetString("PhotoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photos improve your chances of selling your real estate.
        /// </summary>
        public static string PhotosToolTip {
            get {
                return ResourceManager.GetString("PhotosToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is Required.
        /// </summary>
        public static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the estimated  total price for selling?.
        /// </summary>
        public static string PriceTooltip {
            get {
                return ResourceManager.GetString("PriceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this field is Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Successfully.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, No data exist.
        /// </summary>
        public static string ResultNotFound {
            get {
                return ResourceManager.GetString("ResultNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Successfully.
        /// </summary>
        public static string SendSuccessfully {
            get {
                return ResourceManager.GetString("SendSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to the website.
        /// </summary>
        public static string SigninMessage {
            get {
                return ResourceManager.GetString("SigninMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slogan is Required.
        /// </summary>
        public static string SloganRequired {
            get {
                return ResourceManager.GetString("SloganRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Street Name is Required.
        /// </summary>
        public static string StreetNameRequired {
            get {
                return ResourceManager.GetString("StreetNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary is Required .
        /// </summary>
        public static string SummaryRequired {
            get {
                return ResourceManager.GetString("SummaryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company data was suspended for the following reason:.
        /// </summary>
        public static string SuspendedCompanyMsg {
            get {
                return ResourceManager.GetString("SuspendedCompanyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended Successfully.
        /// </summary>
        public static string SuspendedSuccessfully {
            get {
                return ResourceManager.GetString("SuspendedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account was Suspended for the following Reason.
        /// </summary>
        public static string SuspendedUserMessage {
            get {
                return ResourceManager.GetString("SuspendedUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For More Information Please Contact Our .
        /// </summary>
        public static string SuspendInfoMsg {
            get {
                return ResourceManager.GetString("SuspendInfoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this was suspended for the following reason: .
        /// </summary>
        public static string SuspendMsg {
            get {
                return ResourceManager.GetString("SuspendMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        public static string ThanksTitleMsg {
            get {
                return ResourceManager.GetString("ThanksTitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you must enter the total number.
        /// </summary>
        public static string TotalNumberRequired {
            get {
                return ResourceManager.GetString("TotalNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        public static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is Required.
        /// </summary>
        public static string URLRequired {
            get {
                return ResourceManager.GetString("URLRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account was Created Successfully, A temp password will be sent to the user&apos;s email and mobile.
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName Not Exist.
        /// </summary>
        public static string UserNameNotExsit {
            get {
                return ResourceManager.GetString("UserNameNotExsit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is Required.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fields values is not correct.
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be more than 10 letter.
        /// </summary>
        public static string ValidDescription {
            get {
                return ResourceManager.GetString("ValidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not correct.
        /// </summary>
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose either a GIF, JPG or PNG image..
        /// </summary>
        public static string ValidImage {
            get {
                return ResourceManager.GetString("ValidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Image Dimensions is not correct.
        /// </summary>
        public static string ValidImageDimension {
            get {
                return ResourceManager.GetString("ValidImageDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size must be less than 1 MB.
        /// </summary>
        public static string ValidImageSize {
            get {
                return ResourceManager.GetString("ValidImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Name.
        /// </summary>
        public static string ValidName {
            get {
                return ResourceManager.GetString("ValidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be more than 6 letter.
        /// </summary>
        public static string ValidPassword {
            get {
                return ResourceManager.GetString("ValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To view Company Contact Data.
        /// </summary>
        public static string ViewCompanyData {
            get {
                return ResourceManager.GetString("ViewCompanyData", resourceCulture);
            }
        }
    }
}
